# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: madowu 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "madowu"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["ippei94da"]
  s.date = "2016-02-26"
  s.description = "Markdown to HTML with table of contents, sidebar to neighboring directories."
  s.email = "ippei94da@gmail.com"
  s.executables = ["dirmap", "madowu", "tex2image"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CHANGES",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/dirmap",
    "bin/madowu",
    "bin/tex2image",
    "doc/.dirmap.md",
    "doc/.gitignore",
    "doc/Rakefile",
    "doc/index.md",
    "doc/madowu.css",
    "example/.gitignore",
    "example/Rakefile",
    "example/enum.md",
    "example/eq.tex",
    "example/heading.md",
    "example/index.md",
    "example/list.md",
    "example/madowu.css",
    "example/subdir/Rakefile",
    "example/subdir/index.md",
    "example/subdir/madowu.css",
    "example/subdir/subdir2/Rakefile",
    "example/subdir/subdir2/index.md",
    "example/subdir/subdir2/madowu.css",
    "example/tex2image/.gitignore",
    "example/tex2image/eq.tex",
    "lib/madowu.rb",
    "lib/madowu/directorymapper.rb",
    "lib/madowu/htmlgenerator.rb",
    "madowu.gemspec",
    "test/directorymapper/.gitignore",
    "test/directorymapper/dir1/foo.md",
    "test/directorymapper/dir2/dir/index.md",
    "test/directorymapper/dir2/foo.md",
    "test/directorymapper/dir2/index.html",
    "test/directorymapper/empty.md",
    "test/directorymapper/file1.md",
    "test/directorymapper/head.md",
    "test/directorymapper/title.html",
    "test/empty.md",
    "test/head.md",
    "test/head1.md",
    "test/helper.rb",
    "test/subdir/empty.md",
    "test/test.css",
    "test/test_directorymapper.rb",
    "test/test_htmlgenerator.rb",
    "test/test_madowu.rb"
  ]
  s.homepage = "http://github.com/ippei94da/madowu"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Madowu, MArkDOWn to markUp, to build html"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<test-unit>, ["~> 3.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.11"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
    else
      s.add_dependency(%q<test-unit>, ["~> 3.1"])
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<bundler>, ["~> 1.11"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
    end
  else
    s.add_dependency(%q<test-unit>, ["~> 3.1"])
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<bundler>, ["~> 1.11"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
  end
end

